/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.daos;


import ca.nanometrics.halo.db.tables.Organization;
import ca.nanometrics.halo.db.tables.records.OrganizationRecord;

import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;

import java.time.Instant;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.jdbc.JDBCRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationDao extends AbstractVertxDAO<OrganizationRecord, ca.nanometrics.halo.db.tables.pojos.Organization, Integer, Single<List<ca.nanometrics.halo.db.tables.pojos.Organization>>, Single<Optional<ca.nanometrics.halo.db.tables.pojos.Organization>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<OrganizationRecord,ca.nanometrics.halo.db.tables.pojos.Organization,Integer> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public OrganizationDao(Configuration configuration, io.vertx.reactivex.core.Vertx vertx) {
        super(Organization.ORGANIZATION, ca.nanometrics.halo.db.tables.pojos.Organization.class, new JDBCRXQueryExecutor<OrganizationRecord,ca.nanometrics.halo.db.tables.pojos.Organization,Integer>(configuration,ca.nanometrics.halo.db.tables.pojos.Organization.class,vertx));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ca.nanometrics.halo.db.tables.pojos.Organization object) {
        return object.getOrganizationId();
    }

    /**
     * Find records that have <code>organization_name IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.Organization>> findManyByOrganizationName(List<String> values) {
        return findManyByCondition(Organization.ORGANIZATION.ORGANIZATION_NAME.in(values));
    }

    /**
     * Find a unique record that has <code>organization_name = value</code> asynchronously
     */
    public Single<Optional<ca.nanometrics.halo.db.tables.pojos.Organization>> findOneByOrganizationName(String value) {
        return findOneByCondition(Organization.ORGANIZATION.ORGANIZATION_NAME.eq(value));
    }

    /**
     * Find records that have <code>created_at IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.Organization>> findManyByCreatedAt(List<Instant> values) {
        return findManyByCondition(Organization.ORGANIZATION.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>updated_at IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.Organization>> findManyByUpdatedAt(List<Instant> values) {
        return findManyByCondition(Organization.ORGANIZATION.UPDATED_AT.in(values));
    }

    @Override
    public JDBCRXQueryExecutor<OrganizationRecord,ca.nanometrics.halo.db.tables.pojos.Organization,Integer> queryExecutor(){
        return (JDBCRXQueryExecutor<OrganizationRecord,ca.nanometrics.halo.db.tables.pojos.Organization,Integer>) super.queryExecutor();
    }
}
