/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.daos;


import ca.nanometrics.halo.db.tables.User;
import ca.nanometrics.halo.db.tables.records.UserRecord;

import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;

import java.time.Instant;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.jdbc.JDBCRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends AbstractVertxDAO<UserRecord, ca.nanometrics.halo.db.tables.pojos.User, Integer, Single<List<ca.nanometrics.halo.db.tables.pojos.User>>, Single<Optional<ca.nanometrics.halo.db.tables.pojos.User>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<UserRecord,ca.nanometrics.halo.db.tables.pojos.User,Integer> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public UserDao(Configuration configuration, io.vertx.reactivex.core.Vertx vertx) {
        super(User.USER, ca.nanometrics.halo.db.tables.pojos.User.class, new JDBCRXQueryExecutor<UserRecord,ca.nanometrics.halo.db.tables.pojos.User,Integer>(configuration,ca.nanometrics.halo.db.tables.pojos.User.class,vertx));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ca.nanometrics.halo.db.tables.pojos.User object) {
        return object.getUserId();
    }

    /**
     * Find records that have <code>organization_id IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByOrganizationId(List<Integer> values) {
        return findManyByCondition(User.USER.ORGANIZATION_ID.in(values));
    }

    /**
     * Find records that have <code>first_name IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByFirstName(List<String> values) {
        return findManyByCondition(User.USER.FIRST_NAME.in(values));
    }

    /**
     * Find records that have <code>last_name IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByLastName(List<String> values) {
        return findManyByCondition(User.USER.LAST_NAME.in(values));
    }

    /**
     * Find records that have <code>email IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByEmail(List<String> values) {
        return findManyByCondition(User.USER.EMAIL.in(values));
    }

    /**
     * Find a unique record that has <code>email = value</code> asynchronously
     */
    public Single<Optional<ca.nanometrics.halo.db.tables.pojos.User>> findOneByEmail(String value) {
        return findOneByCondition(User.USER.EMAIL.eq(value));
    }

    /**
     * Find records that have <code>created_at IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByCreatedAt(List<Instant> values) {
        return findManyByCondition(User.USER.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>updated_at IN (values)</code> asynchronously
     */
    public Single<List<ca.nanometrics.halo.db.tables.pojos.User>> findManyByUpdatedAt(List<Instant> values) {
        return findManyByCondition(User.USER.UPDATED_AT.in(values));
    }

    @Override
    public JDBCRXQueryExecutor<UserRecord,ca.nanometrics.halo.db.tables.pojos.User,Integer> queryExecutor(){
        return (JDBCRXQueryExecutor<UserRecord,ca.nanometrics.halo.db.tables.pojos.User,Integer>) super.queryExecutor();
    }
}
