/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ca.nanometrics.halo.db.tables.Asset;
import ca.nanometrics.halo.db.tables.AssetType;
import ca.nanometrics.halo.db.tables.Organization;
import ca.nanometrics.halo.db.tables.User;

/**
 * A class modelling indexes of tables of the <code>halo</code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.7" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes
{

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index ASSET_PKEY = Indexes0.ASSET_PKEY;
  public static final Index ASSET_SERIAL_NUMBER_KEY = Indexes0.ASSET_SERIAL_NUMBER_KEY;
  public static final Index ASSET_TYPE_ASSET_TYPE_NAME_KEY = Indexes0.ASSET_TYPE_ASSET_TYPE_NAME_KEY;
  public static final Index ASSET_TYPE_PKEY = Indexes0.ASSET_TYPE_PKEY;
  public static final Index ORGANIZATION_ORGANIZATION_NAME_KEY = Indexes0.ORGANIZATION_ORGANIZATION_NAME_KEY;
  public static final Index ORGANIZATION_PKEY = Indexes0.ORGANIZATION_PKEY;
  public static final Index USER_EMAIL_KEY = Indexes0.USER_EMAIL_KEY;
  public static final Index USER_PKEY = Indexes0.USER_PKEY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0
  {
    public static Index ASSET_PKEY =
        Internal.createIndex("asset_pkey", Asset.ASSET, new OrderField[] { Asset.ASSET.ASSET_ID }, true);
    public static Index ASSET_SERIAL_NUMBER_KEY = Internal.createIndex("asset_serial_number_key", Asset.ASSET,
        new OrderField[] { Asset.ASSET.SERIAL_NUMBER }, true);
    public static Index ASSET_TYPE_ASSET_TYPE_NAME_KEY = Internal.createIndex("asset_type_asset_type_name_key",
        AssetType.ASSET_TYPE, new OrderField[] { AssetType.ASSET_TYPE.ASSET_TYPE_NAME }, true);
    public static Index ASSET_TYPE_PKEY = Internal.createIndex("asset_type_pkey", AssetType.ASSET_TYPE,
        new OrderField[] { AssetType.ASSET_TYPE.ASSET_TYPE_ID }, true);
    public static Index ORGANIZATION_ORGANIZATION_NAME_KEY = Internal.createIndex("organization_organization_name_key",
        Organization.ORGANIZATION, new OrderField[] { Organization.ORGANIZATION.ORGANIZATION_NAME }, true);
    public static Index ORGANIZATION_PKEY = Internal.createIndex("organization_pkey", Organization.ORGANIZATION,
        new OrderField[] { Organization.ORGANIZATION.ORGANIZATION_ID }, true);
    public static Index USER_EMAIL_KEY =
        Internal.createIndex("user_email_key", User.USER, new OrderField[] { User.USER.EMAIL }, true);
    public static Index USER_PKEY =
        Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.USER_ID }, true);
  }
}
