/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in halo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>halo.asset_id_seq</code>
     */
    public static final Sequence<Long> ASSET_ID_SEQ = new SequenceImpl<Long>("asset_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.asset_instance_id_seq</code>
     */
    public static final Sequence<Long> ASSET_INSTANCE_ID_SEQ = new SequenceImpl<Long>("asset_instance_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.asset_type_id_seq</code>
     */
    public static final Sequence<Long> ASSET_TYPE_ID_SEQ = new SequenceImpl<Long>("asset_type_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.deployment_id_seq</code>
     */
    public static final Sequence<Long> DEPLOYMENT_ID_SEQ = new SequenceImpl<Long>("deployment_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.organization_id_seq</code>
     */
    public static final Sequence<Long> ORGANIZATION_ID_SEQ = new SequenceImpl<Long>("organization_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.station_id_seq</code>
     */
    public static final Sequence<Long> STATION_ID_SEQ = new SequenceImpl<Long>("station_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.template_id_seq</code>
     */
    public static final Sequence<Long> TEMPLATE_ID_SEQ = new SequenceImpl<Long>("template_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>halo.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Halo.HALO, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
