/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables;


import ca.nanometrics.halo.db.Halo;
import ca.nanometrics.halo.db.Indexes;
import ca.nanometrics.halo.db.Keys;
import ca.nanometrics.halo.db.tables.records.AssetRecord;
import ca.nanometrics.util.jooq.converter.InstantLocalDateTimeConverter;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset extends TableImpl<AssetRecord> {

    private static final long serialVersionUID = 34390783;

    /**
     * The reference instance of <code>halo.asset</code>
     */
    public static final Asset ASSET = new Asset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetRecord> getRecordType() {
        return AssetRecord.class;
    }

    /**
     * The column <code>halo.asset.asset_id</code>.
     */
    public final TableField<AssetRecord, Integer> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('halo.asset_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>halo.asset.organization_id</code>.
     */
    public final TableField<AssetRecord, Integer> ORGANIZATION_ID = createField("organization_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>halo.asset.asset_type_id</code>.
     */
    public final TableField<AssetRecord, Integer> ASSET_TYPE_ID = createField("asset_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>halo.asset.serial_number</code>.
     */
    public final TableField<AssetRecord, Integer> SERIAL_NUMBER = createField("serial_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>halo.asset.created_at</code>.
     */
    public final TableField<AssetRecord, Instant> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "", new InstantLocalDateTimeConverter());

    /**
     * The column <code>halo.asset.updated_at</code>.
     */
    public final TableField<AssetRecord, Instant> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "", new InstantLocalDateTimeConverter());

    /**
     * Create a <code>halo.asset</code> table reference
     */
    public Asset() {
        this(DSL.name("asset"), null);
    }

    /**
     * Create an aliased <code>halo.asset</code> table reference
     */
    public Asset(String alias) {
        this(DSL.name(alias), ASSET);
    }

    /**
     * Create an aliased <code>halo.asset</code> table reference
     */
    public Asset(Name alias) {
        this(alias, ASSET);
    }

    private Asset(Name alias, Table<AssetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Asset(Name alias, Table<AssetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Asset(Table<O> child, ForeignKey<O, AssetRecord> key) {
        super(child, key, ASSET);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Halo.HALO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASSET_PKEY, Indexes.ASSET_SERIAL_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AssetRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AssetRecord> getPrimaryKey() {
        return Keys.ASSET_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AssetRecord>> getKeys() {
        return Arrays.<UniqueKey<AssetRecord>>asList(Keys.ASSET_PKEY, Keys.ASSET_SERIAL_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AssetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AssetRecord, ?>>asList(Keys.ASSET__ASSET_ORGANIZATION_ID_FKEY, Keys.ASSET__ASSET_ASSET_TYPE_ID_FKEY);
    }

    public Organization organization() {
        return new Organization(this, Keys.ASSET__ASSET_ORGANIZATION_ID_FKEY);
    }

    public AssetType assetType() {
        return new AssetType(this, Keys.ASSET__ASSET_ASSET_TYPE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Asset as(String alias) {
        return new Asset(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Asset as(Name alias) {
        return new Asset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Asset rename(String name) {
        return new Asset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Asset rename(Name name) {
        return new Asset(name, null);
    }
}
