/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset implements VertxPojo, Serializable {

    private static final long serialVersionUID = 1712754995;

    private Integer assetId;
    private Integer organizationId;
    private Integer assetTypeId;
    private Integer serialNumber;
    private Instant createdAt;
    private Instant updatedAt;

    public Asset() {}

    public Asset(Asset value) {
        this.assetId = value.assetId;
        this.organizationId = value.organizationId;
        this.assetTypeId = value.assetTypeId;
        this.serialNumber = value.serialNumber;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Asset(
        Integer assetId,
        Integer organizationId,
        Integer assetTypeId,
        Integer serialNumber,
        Instant createdAt,
        Instant updatedAt
    ) {
        this.assetId = assetId;
        this.organizationId = organizationId;
        this.assetTypeId = assetTypeId;
        this.serialNumber = serialNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getAssetId() {
        return this.assetId;
    }

    public Asset setAssetId(Integer assetId) {
        this.assetId = assetId;
        return this;
    }

    public Integer getOrganizationId() {
        return this.organizationId;
    }

    public Asset setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
        return this;
    }

    public Integer getAssetTypeId() {
        return this.assetTypeId;
    }

    public Asset setAssetTypeId(Integer assetTypeId) {
        this.assetTypeId = assetTypeId;
        return this;
    }

    public Integer getSerialNumber() {
        return this.serialNumber;
    }

    public Asset setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
        return this;
    }

    public Instant getCreatedAt() {
        return this.createdAt;
    }

    public Asset setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Instant getUpdatedAt() {
        return this.updatedAt;
    }

    public Asset setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Asset other = (Asset) obj;
        if (assetId == null) {
            if (other.assetId != null)
                return false;
        }
        else if (!assetId.equals(other.assetId))
            return false;
        if (organizationId == null) {
            if (other.organizationId != null)
                return false;
        }
        else if (!organizationId.equals(other.organizationId))
            return false;
        if (assetTypeId == null) {
            if (other.assetTypeId != null)
                return false;
        }
        else if (!assetTypeId.equals(other.assetTypeId))
            return false;
        if (serialNumber == null) {
            if (other.serialNumber != null)
                return false;
        }
        else if (!serialNumber.equals(other.serialNumber))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.assetId == null) ? 0 : this.assetId.hashCode());
        result = prime * result + ((this.organizationId == null) ? 0 : this.organizationId.hashCode());
        result = prime * result + ((this.assetTypeId == null) ? 0 : this.assetTypeId.hashCode());
        result = prime * result + ((this.serialNumber == null) ? 0 : this.serialNumber.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Asset (");

        sb.append(assetId);
        sb.append(", ").append(organizationId);
        sb.append(", ").append(assetTypeId);
        sb.append(", ").append(serialNumber);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public Asset(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Asset fromJson(io.vertx.core.json.JsonObject json) {
        setAssetId(json.getInteger("asset_id"));
        setOrganizationId(json.getInteger("organization_id"));
        setAssetTypeId(json.getInteger("asset_type_id"));
        setSerialNumber(json.getInteger("serial_number"));
        setCreatedAt(json.getInstant("created_at"));
        setUpdatedAt(json.getInstant("updated_at"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("asset_id",getAssetId());
        json.put("organization_id",getOrganizationId());
        json.put("asset_type_id",getAssetTypeId());
        json.put("serial_number",getSerialNumber());
        json.put("created_at",getCreatedAt());
        json.put("updated_at",getUpdatedAt());
        return json;
    }

}
