/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetType implements VertxPojo, Serializable {

    private static final long serialVersionUID = 1578506969;

    private Integer assetTypeId;
    private String  assetTypeName;
    private Instant createdAt;
    private Instant updatedAt;

    public AssetType() {}

    public AssetType(AssetType value) {
        this.assetTypeId = value.assetTypeId;
        this.assetTypeName = value.assetTypeName;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public AssetType(
        Integer assetTypeId,
        String  assetTypeName,
        Instant createdAt,
        Instant updatedAt
    ) {
        this.assetTypeId = assetTypeId;
        this.assetTypeName = assetTypeName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getAssetTypeId() {
        return this.assetTypeId;
    }

    public AssetType setAssetTypeId(Integer assetTypeId) {
        this.assetTypeId = assetTypeId;
        return this;
    }

    public String getAssetTypeName() {
        return this.assetTypeName;
    }

    public AssetType setAssetTypeName(String assetTypeName) {
        this.assetTypeName = assetTypeName;
        return this;
    }

    public Instant getCreatedAt() {
        return this.createdAt;
    }

    public AssetType setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Instant getUpdatedAt() {
        return this.updatedAt;
    }

    public AssetType setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AssetType other = (AssetType) obj;
        if (assetTypeId == null) {
            if (other.assetTypeId != null)
                return false;
        }
        else if (!assetTypeId.equals(other.assetTypeId))
            return false;
        if (assetTypeName == null) {
            if (other.assetTypeName != null)
                return false;
        }
        else if (!assetTypeName.equals(other.assetTypeName))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.assetTypeId == null) ? 0 : this.assetTypeId.hashCode());
        result = prime * result + ((this.assetTypeName == null) ? 0 : this.assetTypeName.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetType (");

        sb.append(assetTypeId);
        sb.append(", ").append(assetTypeName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public AssetType(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public AssetType fromJson(io.vertx.core.json.JsonObject json) {
        setAssetTypeId(json.getInteger("asset_type_id"));
        setAssetTypeName(json.getString("asset_type_name"));
        setCreatedAt(json.getInstant("created_at"));
        setUpdatedAt(json.getInstant("updated_at"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("asset_type_id",getAssetTypeId());
        json.put("asset_type_name",getAssetTypeName());
        json.put("created_at",getCreatedAt());
        json.put("updated_at",getUpdatedAt());
        return json;
    }

}
