/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationAsset implements VertxPojo, Serializable {

    private static final long serialVersionUID = 545330981;

    private Integer stationId;
    private Integer assetInstanceId;
    private Instant createdAt;
    private Instant updatedAt;

    public StationAsset() {}

    public StationAsset(StationAsset value) {
        this.stationId = value.stationId;
        this.assetInstanceId = value.assetInstanceId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public StationAsset(
        Integer stationId,
        Integer assetInstanceId,
        Instant createdAt,
        Instant updatedAt
    ) {
        this.stationId = stationId;
        this.assetInstanceId = assetInstanceId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getStationId() {
        return this.stationId;
    }

    public StationAsset setStationId(Integer stationId) {
        this.stationId = stationId;
        return this;
    }

    public Integer getAssetInstanceId() {
        return this.assetInstanceId;
    }

    public StationAsset setAssetInstanceId(Integer assetInstanceId) {
        this.assetInstanceId = assetInstanceId;
        return this;
    }

    public Instant getCreatedAt() {
        return this.createdAt;
    }

    public StationAsset setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Instant getUpdatedAt() {
        return this.updatedAt;
    }

    public StationAsset setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StationAsset other = (StationAsset) obj;
        if (stationId == null) {
            if (other.stationId != null)
                return false;
        }
        else if (!stationId.equals(other.stationId))
            return false;
        if (assetInstanceId == null) {
            if (other.assetInstanceId != null)
                return false;
        }
        else if (!assetInstanceId.equals(other.assetInstanceId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.stationId == null) ? 0 : this.stationId.hashCode());
        result = prime * result + ((this.assetInstanceId == null) ? 0 : this.assetInstanceId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StationAsset (");

        sb.append(stationId);
        sb.append(", ").append(assetInstanceId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public StationAsset(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public StationAsset fromJson(io.vertx.core.json.JsonObject json) {
        setStationId(json.getInteger("station_id"));
        setAssetInstanceId(json.getInteger("asset_instance_id"));
        setCreatedAt(json.getInstant("created_at"));
        setUpdatedAt(json.getInstant("updated_at"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("station_id",getStationId());
        json.put("asset_instance_id",getAssetInstanceId());
        json.put("created_at",getCreatedAt());
        json.put("updated_at",getUpdatedAt());
        return json;
    }

}
