/*
 * This file is generated by jOOQ.
 */
package ca.nanometrics.halo.db.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template implements VertxPojo, Serializable {

    private static final long serialVersionUID = 602529905;

    private Integer templateId;
    private String  templateName;
    private Integer organizationId;
    private Integer assetTypeId;
    private Object  configuration;
    private Instant createdAt;
    private Instant updatedAt;

    public Template() {}

    public Template(Template value) {
        this.templateId = value.templateId;
        this.templateName = value.templateName;
        this.organizationId = value.organizationId;
        this.assetTypeId = value.assetTypeId;
        this.configuration = value.configuration;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Template(
        Integer templateId,
        String  templateName,
        Integer organizationId,
        Integer assetTypeId,
        Object  configuration,
        Instant createdAt,
        Instant updatedAt
    ) {
        this.templateId = templateId;
        this.templateName = templateName;
        this.organizationId = organizationId;
        this.assetTypeId = assetTypeId;
        this.configuration = configuration;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getTemplateId() {
        return this.templateId;
    }

    public Template setTemplateId(Integer templateId) {
        this.templateId = templateId;
        return this;
    }

    public String getTemplateName() {
        return this.templateName;
    }

    public Template setTemplateName(String templateName) {
        this.templateName = templateName;
        return this;
    }

    public Integer getOrganizationId() {
        return this.organizationId;
    }

    public Template setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
        return this;
    }

    public Integer getAssetTypeId() {
        return this.assetTypeId;
    }

    public Template setAssetTypeId(Integer assetTypeId) {
        this.assetTypeId = assetTypeId;
        return this;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getConfiguration() {
        return this.configuration;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Template setConfiguration(Object configuration) {
        this.configuration = configuration;
        return this;
    }

    public Instant getCreatedAt() {
        return this.createdAt;
    }

    public Template setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Instant getUpdatedAt() {
        return this.updatedAt;
    }

    public Template setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Template other = (Template) obj;
        if (templateId == null) {
            if (other.templateId != null)
                return false;
        }
        else if (!templateId.equals(other.templateId))
            return false;
        if (templateName == null) {
            if (other.templateName != null)
                return false;
        }
        else if (!templateName.equals(other.templateName))
            return false;
        if (organizationId == null) {
            if (other.organizationId != null)
                return false;
        }
        else if (!organizationId.equals(other.organizationId))
            return false;
        if (assetTypeId == null) {
            if (other.assetTypeId != null)
                return false;
        }
        else if (!assetTypeId.equals(other.assetTypeId))
            return false;
        if (configuration == null) {
            if (other.configuration != null)
                return false;
        }
        else if (!configuration.equals(other.configuration))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.templateId == null) ? 0 : this.templateId.hashCode());
        result = prime * result + ((this.templateName == null) ? 0 : this.templateName.hashCode());
        result = prime * result + ((this.organizationId == null) ? 0 : this.organizationId.hashCode());
        result = prime * result + ((this.assetTypeId == null) ? 0 : this.assetTypeId.hashCode());
        result = prime * result + ((this.configuration == null) ? 0 : this.configuration.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Template (");

        sb.append(templateId);
        sb.append(", ").append(templateName);
        sb.append(", ").append(organizationId);
        sb.append(", ").append(assetTypeId);
        sb.append(", ").append(configuration);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public Template(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Template fromJson(io.vertx.core.json.JsonObject json) {
        setTemplateId(json.getInteger("template_id"));
        setTemplateName(json.getString("template_name"));
        setOrganizationId(json.getInteger("organization_id"));
        setAssetTypeId(json.getInteger("asset_type_id"));
        // Omitting unrecognized type java.lang.Object for column configuration!
        setCreatedAt(json.getInstant("created_at"));
        setUpdatedAt(json.getInstant("updated_at"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("template_id",getTemplateId());
        json.put("template_name",getTemplateName());
        json.put("organization_id",getOrganizationId());
        json.put("asset_type_id",getAssetTypeId());
        // Omitting unrecognized type java.lang.Object for column configuration!
        json.put("created_at",getCreatedAt());
        json.put("updated_at",getUpdatedAt());
        return json;
    }

}
